### ISSUE TITLE
Handle IV Crashes

### ISSUE THREAD

**Issue by teddyrowan** [MySybil/tradier-options-plotter#4]
Print error and escape from IV printing. 

```
Now downloading trade data for: PLTR $30.0C (2022-01-21)
Traceback (most recent call last):
  File "run_sybil_plotter.py", line 76, in <module>
    tpm.plot_data(trade_data, 
  File "~/Python/tradier-options-plotter/tp_plot_manager.py", line 36, in plot_data
    plot_timesales(data,
  File "~/Python/tradier-options-plotter/tp_plot_manager.py", line 189, in plot_timesales
    pandas_data = quote_time, quote['open'], quote['high'], quote['low'], quote['close'], quote['volume'], round(iv_close*100,2)
UnboundLocalError: local variable 'iv_close' referenced before assignment
```

**Comment by teddyrowan** [comment]
Potentially fixed in a8f206c4ae2fd33ca7217a1dee8b3cb6881af506. Requires additional testing.
